<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Button with Dynamic ID</name>
   <tag></tag>
   <elementGuidId>e5d2f1c5-d7f7-456e-a88d-fcd8666e11a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > section:nth-child(2) > div:nth-child(1) > button:nth-child(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/section[1]/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94a4bda6-c274-4049-93b3-b8988b663f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>6af78e72-899f-4d9d-875d-a7060eb2f35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e072ce3-8a84-434e-93a7-e7d9b6b06b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>79b77d6a-76df-2571-cbba-5906c430ea65</value>
      <webElementGuid>cd42604c-44bd-4315-bc7b-0a47a71e8e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Button with Dynamic ID</value>
      <webElementGuid>8fd525c8-3833-4c49-9275-dbbf694a730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;79b77d6a-76df-2571-cbba-5906c430ea65&quot;)</value>
      <webElementGuid>134c72ec-85fd-457a-87e2-8c6696cf5b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='79b77d6a-76df-2571-cbba-5906c430ea65']</value>
      <webElementGuid>4efaa90c-9e03-4824-9440-15c0a2fd2c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playground'])[1]/following::button[1]</value>
      <webElementGuid>bb41e3b4-a78c-4875-8ee6-55360973ed1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Then execute your test to make sure that ID is not used for button identification.'])[1]/following::button[1]</value>
      <webElementGuid>e6db6560-4fec-47f5-b7ae-09e3b19004f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fork the website on GitHub'])[1]/preceding::button[1]</value>
      <webElementGuid>70a320db-ac28-495c-9134-27399bbd7384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Button with Dynamic ID']/parent::*</value>
      <webElementGuid>57fd64f1-85c3-485d-90b7-cfa5178d5d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>893b2460-bff5-46b8-b07b-b3093b857bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '79b77d6a-76df-2571-cbba-5906c430ea65' and (text() = 'Button with Dynamic ID' or . = 'Button with Dynamic ID')]</value>
      <webElementGuid>f42e9d33-aa0f-4529-adce-5e013cb56a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
