<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dynamic ID</name>
   <tag></tag>
   <elementGuidId>3214a807-b978-4036-86fc-33ab3a6ea0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='overview']/div/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17608376-1aa3-43a2-b4d2-520065082719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dynamicid</value>
      <webElementGuid>933eaf1d-a017-40ef-83bf-6ee3907f8243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dynamic ID</value>
      <webElementGuid>19d2a793-f80a-494a-beae-4a11e6bc321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm&quot;]/h3[1]/a[1]</value>
      <webElementGuid>0bd9b14c-4d3e-4cbd-b7b5-87e171dcb475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='overview']/div/div/div/h3/a</value>
      <webElementGuid>1c926525-a459-4bbc-9da2-54a7cfbac1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dynamic ID')]</value>
      <webElementGuid>a8e946bb-6f56-4e6c-a24f-7ceff35daa57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC 4.0 BY-NC'])[1]/following::a[1]</value>
      <webElementGuid>3fd1c1d9-72ec-40a0-84fc-f93a12b558de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Rubik', &quot;'&quot;, 's Cube')])[1]/following::a[2]</value>
      <webElementGuid>eaf688e6-8357-4df4-ba70-4bc4f6e08457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Attribute'])[1]/preceding::a[1]</value>
      <webElementGuid>f749a601-dbf8-41db-9365-a3e88833d7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hidden Layers'])[1]/preceding::a[2]</value>
      <webElementGuid>76dd2864-bacb-4c14-8e7c-b801320a0d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dynamic ID']/parent::*</value>
      <webElementGuid>570057be-0f7c-446e-a1bc-dfdaf8c44606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dynamicid')]</value>
      <webElementGuid>f53ee6d9-2dc2-4001-9559-c6d5256e8b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>369668c3-9344-4415-973f-74a5dd91b84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dynamicid' and (text() = 'Dynamic ID' or . = 'Dynamic ID')]</value>
      <webElementGuid>7995572f-133b-4b4b-89a5-e7c60421cdab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
